# site settings
title: Rob Southgate Creative Developer
subtitle: Creative coding
email: robsouthgate4@gmail.com
description: Creative Developer for The Mill London
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://robsouthgate4.github.io/" # the base hostname & protocol for your site
author: Robert Southgate
street_address: 
city: London
state: null
zip_code: null
country: United Kingdom
phone: null

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: null
facebook_url: null
github_url: https://github.com/robsouthgate4
gitlab_url: null
googleplus_url: null
instagram_url: https://www.instagram.com/robs_creative/
linkedin_url: https://www.linkedin.com/in/robsouthgateweb/
pinterest_url: null
slack_url: null
twitter_url: null

# build settings
markdown: kramdown

sass:
  style: compressed
